### ISSUE TITLE
[BUG] SDKClient test failures due to Apache HttpClient / Core 5.x upgrade

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/opensearch-sdk-java#210]
### What is the bug?

SDKClient tests using apache HttpClient need to be ugraded to Core 5.x

```
TestSDKClient > testCreateClient() FAILED
    java.lang.NoClassDefFoundError: org/apache/http/HttpHost
        at org.opensearch.sdk.SDKClient.initializeClient(SDKClient.java:38)
        at org.opensearch.sdk.TestSDKClient.testCreateClient(TestSDKClient.java:27)

        Caused by:
        java.lang.ClassNotFoundException: org.apache.http.HttpHost
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
            at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
            at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
            ... 2 more

```
### How can one reproduce the bug?
`./gradlew test`

### Do you have any additional context?
Tests are failing since the apache HttpClient has been upgraded via this PR : https://github.com/opensearch-project/OpenSearch/pull/4459

**Comment by joshpalis** [comment]
https://github.com/opensearch-project/opensearch-java/pull/246
