### ISSUE TITLE
[BUG] IllegalArgumentException in AD Settings registration

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#792]
### What is the bug?

```
20:20:43.642 [opensearch[ad-extension][generic][T#4]] DEBUG org.opensearch.transport.TransportService - Action: internal:discovery/enviornmentsettings
20:20:43.647 [opensearch[ad-extension][generic][T#2]] INFO  org.opensearch.sdk.handlers.AcknowledgedResponseHandler - Extension Request failed
org.opensearch.transport.RemoteTransportException: [ip-10-0-134-13.ec2.internal][10.0.134.13:9300][internal:discovery/registercustomsettings]
Caused by: java.lang.IllegalArgumentException: non-node-scoped setting [opendistro.anomaly_detection.enabled] can not have property [Consistent]
        at org.opensearch.common.settings.Setting.checkPropertyRequiresNodeScope(Setting.java:219) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.settings.Setting.<init>(Setting.java:206) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.settings.Setting.<init>(Setting.java:250) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.settings.Setting.<init>(Setting.java:231) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.settings.Setting.<init>(Setting.java:285) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.settings.Setting.boolSetting(Setting.java:2001) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.settings.WriteableSetting.createSetting(WriteableSetting.java:169) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.settings.WriteableSetting.<init>(WriteableSetting.java:113) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.extensions.settings.RegisterCustomSettingsRequest.<init>(RegisterCustomSettingsRequest.java:42) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
```

### How can one reproduce the bug?

Start up AD feature/extensions branch and init with connection to OpenSearch

### What is the expected behavior?

No exceptions

**Comment by dbwiddis** [comment]
This is due to the stale 3.0.0 latest build in use for AD testing, which does not have the change to the `Setting.Property` enum that was put into https://github.com/opensearch-project/OpenSearch/pull/7526 in the middle of the enum order.

Normally enums in Java are type safe and re-orderable, but in the case of settings sent over transport, [the stream uses `ordinal()`](https://github.com/opensearch-project/OpenSearch/blob/e3740f7850f7d5f46fced548d9c829945549484b/server/src/main/java/org/opensearch/common/io/stream/StreamOutput.java#L1241) so ordering matters.

This SDK bug will self-resolve when the 3.0.0 tarball build gets fixed, but I'm thinking that this change in enum values could definitely have some impact in versioning and backwards compatibility (possibly in 2.8.0 vs. 2.7.0?)

@saratvemulapalli and @cwperks do you think we should consider moving that new `ExtensionScope` enum value to the end of the list?  Is this a potential issue for 2.8.0 release?

**Comment by cwperks** [comment]
@dbwiddis Is there a way we can synthetically reproduce this in a unit test to show a fix working by adding this to the end of the enum?

**Comment by dbwiddis** [comment]
just implement writeable and do a writeTo ... that gives you a byte array with the enum ordinals

**Comment by dbwiddis** [comment]
The current bug is that a NodeScope setting with the "old" enum value now gets deserialized as an ExtensionScope.

**Comment by dbwiddis** [comment]
Fixed in https://github.com/opensearch-project/OpenSearch/pull/7871
